# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""macOS-native simulator backends and runnable reference environments."""

from __future__ import annotations

import importlib

_EXPORTS = {
    "BatchedContactSensorState": (".contacts", "BatchedContactSensorState"),
    "mac_env_diagnostics": (".diagnostics", "mac_env_diagnostics"),
    "MacAnymalCRoughEnvCfg": (".env_cfgs", "MacAnymalCRoughEnvCfg"),
    "MacAnymalCFlatEnvCfg": (".env_cfgs", "MacAnymalCFlatEnvCfg"),
    "MacCartDoublePendulumEnvCfg": (".env_cfgs", "MacCartDoublePendulumEnvCfg"),
    "MacCartpoleEnvCfg": (".env_cfgs", "MacCartpoleEnvCfg"),
    "MacCartpoleDepthCameraEnvCfg": (".env_cfgs", "MacCartpoleDepthCameraEnvCfg"),
    "MacCartpoleRGBCameraEnvCfg": (".env_cfgs", "MacCartpoleRGBCameraEnvCfg"),
    "MacFrankaCabinetEnvCfg": (".env_cfgs", "MacFrankaCabinetEnvCfg"),
    "MacFrankaLiftEnvCfg": (".env_cfgs", "MacFrankaLiftEnvCfg"),
    "MacFrankaStackEnvCfg": (".env_cfgs", "MacFrankaStackEnvCfg"),
    "MacFrankaReachEnvCfg": (".env_cfgs", "MacFrankaReachEnvCfg"),
    "MacH1FlatEnvCfg": (".env_cfgs", "MacH1FlatEnvCfg"),
    "MacH1RoughEnvCfg": (".env_cfgs", "MacH1RoughEnvCfg"),
    "MacQuadcopterEnvCfg": (".env_cfgs", "MacQuadcopterEnvCfg"),
    "build_checkpoint_metadata": (".ppo_training", "build_checkpoint_metadata"),
    "checkpoint_metadata_path": (".ppo_training", "checkpoint_metadata_path"),
    "compute_gae": (".ppo_training", "compute_gae"),
    "mean_recent_return": (".ppo_training", "mean_recent_return"),
    "normalize_advantages": (".ppo_training", "normalize_advantages"),
    "play_categorical_policy_checkpoint": (".ppo_training", "play_categorical_policy_checkpoint"),
    "play_gaussian_policy_checkpoint": (".ppo_training", "play_gaussian_policy_checkpoint"),
    "read_checkpoint_metadata": (".ppo_training", "read_checkpoint_metadata"),
    "resolve_resume_hidden_dim": (".ppo_training", "resolve_resume_hidden_dim"),
    "save_policy_checkpoint": (".ppo_training", "save_policy_checkpoint"),
    "write_checkpoint_metadata": (".ppo_training", "write_checkpoint_metadata"),
    "action_rate_l2": (".locomotion", "action_rate_l2"),
    "base_contact_termination": (".locomotion", "base_contact_termination"),
    "feet_air_time_reward": (".locomotion", "feet_air_time_reward"),
    "flat_orientation_l2": (".locomotion", "flat_orientation_l2"),
    "terrain_out_of_bounds": (".locomotion", "terrain_out_of_bounds"),
    "track_linear_velocity_xy_exp": (".locomotion", "track_linear_velocity_xy_exp"),
    "track_yaw_rate_z_exp": (".locomotion", "track_yaw_rate_z_exp"),
    "undesired_contacts": (".locomotion", "undesired_contacts"),
    "DeterministicResetSampler": (".reset_primitives", "DeterministicResetSampler"),
    "MacCameraCaptureError": (".cameras", "MacCameraCaptureError"),
    "CAPTURE_BACKENDS": (".cameras", "CAPTURE_BACKENDS"),
    "CAPTURE_BACKEND_AUTO": (".cameras", "CAPTURE_BACKEND_AUTO"),
    "CAPTURE_BACKEND_AVFOUNDATION": (".cameras", "CAPTURE_BACKEND_AVFOUNDATION"),
    "CAPTURE_BACKEND_ZED_DIRECT": (".cameras", "CAPTURE_BACKEND_ZED_DIRECT"),
    "CAPTURE_BACKEND_ZED_TERMINAL": (".cameras", "CAPTURE_BACKEND_ZED_TERMINAL"),
    "MacCameraDevice": (".cameras", "MacCameraDevice"),
    "MacCameraMode": (".cameras", "MacCameraMode"),
    "capture_mac_camera_raw_frame": (".cameras", "capture_mac_camera_raw_frame"),
    "capture_avfoundation_raw_frame": (".cameras", "capture_avfoundation_raw_frame"),
    "capture_zed_sdk_mlx_raw_frame": (".cameras", "capture_zed_sdk_mlx_raw_frame"),
    "discover_external_cameras": (".cameras", "discover_external_cameras"),
    "list_avfoundation_cameras": (".cameras", "list_avfoundation_cameras"),
    "parse_capture_metadata_text": (".cameras", "parse_capture_metadata_text"),
    "parse_avfoundation_device_list": (".cameras", "parse_avfoundation_device_list"),
    "parse_avfoundation_supported_modes": (".cameras", "parse_avfoundation_supported_modes"),
    "probe_avfoundation_camera_modes": (".cameras", "probe_avfoundation_camera_modes"),
    "read_capture_metadata": (".cameras", "read_capture_metadata"),
    "resolve_zed_sdk_mlx_repo": (".cameras", "resolve_zed_sdk_mlx_repo"),
    "validate_raw_capture_artifacts": (".cameras", "validate_raw_capture_artifacts"),
    "DEFAULT_HEIGHT_SCAN_OFFSETS": (".sensors", "DEFAULT_HEIGHT_SCAN_OFFSETS"),
    "MacPlaneRaycastSensor": (".sensors", "MacPlaneRaycastSensor"),
    "RawStereoFrame": (".stereo_depth", "RawStereoFrame"),
    "compute_disparity_absdiff": (".stereo_depth", "compute_disparity_absdiff"),
    "disparity_to_depth_mm": (".stereo_depth", "disparity_to_depth_mm"),
    "load_raw_stereo_frame": (".stereo_depth", "load_raw_stereo_frame"),
    "normalize_depth_for_preview": (".stereo_depth", "normalize_depth_for_preview"),
    "normalize_disparity_for_preview": (".stereo_depth", "normalize_disparity_for_preview"),
    "save_preview_png": (".stereo_depth", "save_preview_png"),
    "split_stereo_yuyv": (".stereo_depth", "split_stereo_yuyv"),
    "stereo_luma_from_yuyv": (".stereo_depth", "stereo_luma_from_yuyv"),
    "stereo_rgb_from_yuyv": (".stereo_depth", "stereo_rgb_from_yuyv"),
    "yuyv_to_rgb": (".stereo_depth", "yuyv_to_rgb"),
    "RolloutTrace": (".rollout", "RolloutTrace"),
    "replay_actions": (".rollout", "replay_actions"),
    "rollout_env": (".rollout", "rollout_env"),
    "BatchedArticulationState": (".state_primitives", "BatchedArticulationState"),
    "BatchedRootState": (".state_primitives", "BatchedRootState"),
    "EnvironmentOriginGrid": (".state_primitives", "EnvironmentOriginGrid"),
    "MacPlaneTerrain": (".terrain", "MacPlaneTerrain"),
    "MacWaveTerrain": (".terrain", "MacWaveTerrain"),
    "MacAnymalCFlatEnv": (".anymal_c", "MacAnymalCFlatEnv"),
    "MacAnymalCRoughEnv": (".anymal_c", "MacAnymalCRoughEnv"),
    "MacAnymalCFlatSimBackend": (".anymal_c", "MacAnymalCFlatSimBackend"),
    "MacAnymalCPolicy": (".anymal_c", "MacAnymalCPolicy"),
    "MacAnymalCTrainCfg": (".anymal_c", "MacAnymalCTrainCfg"),
    "play_anymal_c_policy": (".anymal_c", "play_anymal_c_policy"),
    "train_anymal_c_policy": (".anymal_c", "train_anymal_c_policy"),
    "MacH1FlatEnv": (".h1", "MacH1FlatEnv"),
    "MacH1RoughEnv": (".h1", "MacH1RoughEnv"),
    "MacH1FlatSimBackend": (".h1", "MacH1FlatSimBackend"),
    "MacH1Policy": (".h1", "MacH1Policy"),
    "MacH1TrainCfg": (".h1", "MacH1TrainCfg"),
    "play_h1_policy": (".h1", "play_h1_policy"),
    "train_h1_policy": (".h1", "train_h1_policy"),
    "MacFrankaCabinetEnv": (".manipulation", "MacFrankaCabinetEnv"),
    "MacFrankaCabinetSimBackend": (".manipulation", "MacFrankaCabinetSimBackend"),
    "MacFrankaCabinetTrainCfg": (".manipulation", "MacFrankaCabinetTrainCfg"),
    "MacFrankaLiftEnv": (".manipulation", "MacFrankaLiftEnv"),
    "MacFrankaLiftSimBackend": (".manipulation", "MacFrankaLiftSimBackend"),
    "MacFrankaLiftTrainCfg": (".manipulation", "MacFrankaLiftTrainCfg"),
    "MacFrankaReachEnv": (".manipulation", "MacFrankaReachEnv"),
    "MacFrankaReachPolicy": (".manipulation", "MacFrankaReachPolicy"),
    "MacFrankaReachSimBackend": (".manipulation", "MacFrankaReachSimBackend"),
    "MacFrankaReachTrainCfg": (".manipulation", "MacFrankaReachTrainCfg"),
    "MacFrankaStackEnv": (".manipulation", "MacFrankaStackEnv"),
    "MacFrankaStackSimBackend": (".manipulation", "MacFrankaStackSimBackend"),
    "MacFrankaStackTrainCfg": (".manipulation", "MacFrankaStackTrainCfg"),
    "play_franka_cabinet_policy": (".manipulation", "play_franka_cabinet_policy"),
    "play_franka_lift_policy": (".manipulation", "play_franka_lift_policy"),
    "play_franka_reach_policy": (".manipulation", "play_franka_reach_policy"),
    "play_franka_stack_policy": (".manipulation", "play_franka_stack_policy"),
    "train_franka_cabinet_policy": (".manipulation", "train_franka_cabinet_policy"),
    "train_franka_lift_policy": (".manipulation", "train_franka_lift_policy"),
    "train_franka_reach_policy": (".manipulation", "train_franka_reach_policy"),
    "train_franka_stack_policy": (".manipulation", "train_franka_stack_policy"),
    "MacCartpoleEnv": (".cartpole", "MacCartpoleEnv"),
    "MacCartpoleCameraEnv": (".cartpole_camera", "MacCartpoleCameraEnv"),
    "MacCartpoleSyntheticCamera": (".cartpole_camera", "MacCartpoleSyntheticCamera"),
    "MacCartpolePolicy": (".cartpole", "MacCartpolePolicy"),
    "MacCartpoleSimBackend": (".cartpole", "MacCartpoleSimBackend"),
    "MacCartpoleTrainCfg": (".cartpole", "MacCartpoleTrainCfg"),
    "play_cartpole_policy": (".cartpole", "play_cartpole_policy"),
    "train_cartpole_policy": (".cartpole", "train_cartpole_policy"),
    "MacCartDoublePendulumEnv": (".cart_double_pendulum", "MacCartDoublePendulumEnv"),
    "MacCartDoublePendulumSimBackend": (".cart_double_pendulum", "MacCartDoublePendulumSimBackend"),
    "MacQuadcopterEnv": (".quadcopter", "MacQuadcopterEnv"),
    "MacQuadcopterSimBackend": (".quadcopter", "MacQuadcopterSimBackend"),
    "SHOWCASE_CFGS": (".showcase", "SHOWCASE_CFGS"),
    "BoxBoxEnvCfg": (".showcase", "BoxBoxEnvCfg"),
    "BoxDiscreteEnvCfg": (".showcase", "BoxDiscreteEnvCfg"),
    "BoxMultiDiscreteEnvCfg": (".showcase", "BoxMultiDiscreteEnvCfg"),
    "DictBoxEnvCfg": (".showcase", "DictBoxEnvCfg"),
    "DictDiscreteEnvCfg": (".showcase", "DictDiscreteEnvCfg"),
    "DictMultiDiscreteEnvCfg": (".showcase", "DictMultiDiscreteEnvCfg"),
    "DiscreteBoxEnvCfg": (".showcase", "DiscreteBoxEnvCfg"),
    "DiscreteDiscreteEnvCfg": (".showcase", "DiscreteDiscreteEnvCfg"),
    "DiscreteMultiDiscreteEnvCfg": (".showcase", "DiscreteMultiDiscreteEnvCfg"),
    "MacCartpoleShowcaseEnv": (".showcase", "MacCartpoleShowcaseEnv"),
    "MultiDiscreteBoxEnvCfg": (".showcase", "MultiDiscreteBoxEnvCfg"),
    "MultiDiscreteDiscreteEnvCfg": (".showcase", "MultiDiscreteDiscreteEnvCfg"),
    "MultiDiscreteMultiDiscreteEnvCfg": (".showcase", "MultiDiscreteMultiDiscreteEnvCfg"),
    "TupleBoxEnvCfg": (".showcase", "TupleBoxEnvCfg"),
    "TupleDiscreteEnvCfg": (".showcase", "TupleDiscreteEnvCfg"),
    "TupleMultiDiscreteEnvCfg": (".showcase", "TupleMultiDiscreteEnvCfg"),
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str):
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(target[0], __name__)
    value = getattr(module, target[1])
    globals()[name] = value
    return value
