# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""macOS-native simulator backends and runnable reference environments."""

from __future__ import annotations

import importlib

_EXPORTS = {
    "BatchedContactSensorState": (".contacts", "BatchedContactSensorState"),
    "mac_env_diagnostics": (".diagnostics", "mac_env_diagnostics"),
    "MacAnymalCRoughEnvCfg": (".env_cfgs", "MacAnymalCRoughEnvCfg"),
    "MacAnymalCFlatEnvCfg": (".env_cfgs", "MacAnymalCFlatEnvCfg"),
    "MacCartDoublePendulumEnvCfg": (".env_cfgs", "MacCartDoublePendulumEnvCfg"),
    "MacCartpoleEnvCfg": (".env_cfgs", "MacCartpoleEnvCfg"),
    "MacCartpoleDepthCameraEnvCfg": (".env_cfgs", "MacCartpoleDepthCameraEnvCfg"),
    "MacCartpoleRGBCameraEnvCfg": (".env_cfgs", "MacCartpoleRGBCameraEnvCfg"),
    "MacAgibotPlaceEnvCfg": (".env_cfgs", "MacAgibotPlaceEnvCfg"),
    "MacAgibotPlaceToy2BoxEnvCfg": (".env_cfgs", "MacAgibotPlaceToy2BoxEnvCfg"),
    "MacAgibotPlaceUprightMugEnvCfg": (".env_cfgs", "MacAgibotPlaceUprightMugEnvCfg"),
    "MacFrankaBinStackEnvCfg": (".env_cfgs", "MacFrankaBinStackEnvCfg"),
    "MacFrankaBinStackPickPlaceEnvCfg": (".env_cfgs", "MacFrankaBinStackPickPlaceEnvCfg"),
    "MacFrankaStackBlueprintEnvCfg": (".env_cfgs", "MacFrankaStackBlueprintEnvCfg"),
    "MacFrankaCabinetEnvCfg": (".env_cfgs", "MacFrankaCabinetEnvCfg"),
    "MacFrankaLiftEnvCfg": (".env_cfgs", "MacFrankaLiftEnvCfg"),
    "MacFactoryPegInsertEnvCfg": (".env_cfgs", "MacFactoryPegInsertEnvCfg"),
    "MacOpenArmBiReachEnvCfg": (".env_cfgs", "MacOpenArmBiReachEnvCfg"),
    "MacOpenArmLiftEnvCfg": (".env_cfgs", "MacOpenArmLiftEnvCfg"),
    "MacOpenArmOpenDrawerEnvCfg": (".env_cfgs", "MacOpenArmOpenDrawerEnvCfg"),
    "MacOpenArmReachEnvCfg": (".env_cfgs", "MacOpenArmReachEnvCfg"),
    "MacFrankaOpenDrawerEnvCfg": (".env_cfgs", "MacFrankaOpenDrawerEnvCfg"),
    "MacFrankaStackEnvCfg": (".env_cfgs", "MacFrankaStackEnvCfg"),
    "MacFrankaStackInstanceRandomizeEnvCfg": (".env_cfgs", "MacFrankaStackInstanceRandomizeEnvCfg"),
    "MacFrankaStackRgbEnvCfg": (".env_cfgs", "MacFrankaStackRgbEnvCfg"),
    "MacFrankaStackSkillgenEnvCfg": (".env_cfgs", "MacFrankaStackSkillgenEnvCfg"),
    "MacFrankaStackVisuomotorCosmosEnvCfg": (".env_cfgs", "MacFrankaStackVisuomotorCosmosEnvCfg"),
    "MacFrankaStackVisuomotorEnvCfg": (".env_cfgs", "MacFrankaStackVisuomotorEnvCfg"),
    "MacFrankaTeddyBearLiftEnvCfg": (".env_cfgs", "MacFrankaTeddyBearLiftEnvCfg"),
    "MacFrankaReachEnvCfg": (".env_cfgs", "MacFrankaReachEnvCfg"),
    "MacUR10ReachEnvCfg": (".env_cfgs", "MacUR10ReachEnvCfg"),
    "MacUR10LongSuctionStackEnvCfg": (".env_cfgs", "MacUR10LongSuctionStackEnvCfg"),
    "MacUR10eGearAssembly2F140EnvCfg": (".env_cfgs", "MacUR10eGearAssembly2F140EnvCfg"),
    "MacUR10eGearAssembly2F140RosInferenceEnvCfg": (
        ".env_cfgs",
        "MacUR10eGearAssembly2F140RosInferenceEnvCfg",
    ),
    "MacUR10eGearAssembly2F85EnvCfg": (".env_cfgs", "MacUR10eGearAssembly2F85EnvCfg"),
    "MacUR10ShortSuctionStackEnvCfg": (".env_cfgs", "MacUR10ShortSuctionStackEnvCfg"),
    "MacUR10eDeployReachEnvCfg": (".env_cfgs", "MacUR10eDeployReachEnvCfg"),
    "MacUR10eDeployReachRosInferenceEnvCfg": (".env_cfgs", "MacUR10eDeployReachRosInferenceEnvCfg"),
    "MacUR10eGearAssembly2F85RosInferenceEnvCfg": (
        ".env_cfgs",
        "MacUR10eGearAssembly2F85RosInferenceEnvCfg",
    ),
    "MacH1FlatEnvCfg": (".env_cfgs", "MacH1FlatEnvCfg"),
    "MacH1RoughEnvCfg": (".env_cfgs", "MacH1RoughEnvCfg"),
    "MacQuadcopterEnvCfg": (".env_cfgs", "MacQuadcopterEnvCfg"),
    "build_checkpoint_metadata": (".ppo_training", "build_checkpoint_metadata"),
    "checkpoint_metadata_path": (".ppo_training", "checkpoint_metadata_path"),
    "compute_gae": (".ppo_training", "compute_gae"),
    "mean_recent_return": (".ppo_training", "mean_recent_return"),
    "normalize_advantages": (".ppo_training", "normalize_advantages"),
    "play_categorical_policy_checkpoint": (".ppo_training", "play_categorical_policy_checkpoint"),
    "play_gaussian_policy_checkpoint": (".ppo_training", "play_gaussian_policy_checkpoint"),
    "read_checkpoint_metadata": (".ppo_training", "read_checkpoint_metadata"),
    "resolve_resume_hidden_dim": (".ppo_training", "resolve_resume_hidden_dim"),
    "save_policy_checkpoint": (".ppo_training", "save_policy_checkpoint"),
    "write_checkpoint_metadata": (".ppo_training", "write_checkpoint_metadata"),
    "action_rate_l2": (".locomotion", "action_rate_l2"),
    "base_contact_termination": (".locomotion", "base_contact_termination"),
    "feet_air_time_reward": (".locomotion", "feet_air_time_reward"),
    "flat_orientation_l2": (".locomotion", "flat_orientation_l2"),
    "terrain_out_of_bounds": (".locomotion", "terrain_out_of_bounds"),
    "track_linear_velocity_xy_exp": (".locomotion", "track_linear_velocity_xy_exp"),
    "track_yaw_rate_z_exp": (".locomotion", "track_yaw_rate_z_exp"),
    "undesired_contacts": (".locomotion", "undesired_contacts"),
    "DeterministicResetSampler": (".reset_primitives", "DeterministicResetSampler"),
    "MacCameraCaptureError": (".cameras", "MacCameraCaptureError"),
    "CAPTURE_BACKENDS": (".cameras", "CAPTURE_BACKENDS"),
    "CAPTURE_BACKEND_AUTO": (".cameras", "CAPTURE_BACKEND_AUTO"),
    "CAPTURE_BACKEND_AVFOUNDATION": (".cameras", "CAPTURE_BACKEND_AVFOUNDATION"),
    "CAPTURE_BACKEND_ZED_DIRECT": (".cameras", "CAPTURE_BACKEND_ZED_DIRECT"),
    "CAPTURE_BACKEND_ZED_TERMINAL": (".cameras", "CAPTURE_BACKEND_ZED_TERMINAL"),
    "MacCameraDevice": (".cameras", "MacCameraDevice"),
    "MacCameraMode": (".cameras", "MacCameraMode"),
    "capture_mac_camera_raw_frame": (".cameras", "capture_mac_camera_raw_frame"),
    "capture_avfoundation_raw_frame": (".cameras", "capture_avfoundation_raw_frame"),
    "capture_zed_sdk_mlx_raw_frame": (".cameras", "capture_zed_sdk_mlx_raw_frame"),
    "discover_external_cameras": (".cameras", "discover_external_cameras"),
    "list_avfoundation_cameras": (".cameras", "list_avfoundation_cameras"),
    "parse_capture_metadata_text": (".cameras", "parse_capture_metadata_text"),
    "parse_avfoundation_device_list": (".cameras", "parse_avfoundation_device_list"),
    "parse_avfoundation_supported_modes": (".cameras", "parse_avfoundation_supported_modes"),
    "probe_avfoundation_camera_modes": (".cameras", "probe_avfoundation_camera_modes"),
    "read_capture_metadata": (".cameras", "read_capture_metadata"),
    "resolve_zed_sdk_mlx_repo": (".cameras", "resolve_zed_sdk_mlx_repo"),
    "validate_raw_capture_artifacts": (".cameras", "validate_raw_capture_artifacts"),
    "DEFAULT_HEIGHT_SCAN_OFFSETS": (".sensors", "DEFAULT_HEIGHT_SCAN_OFFSETS"),
    "MacPlaneRaycastSensor": (".sensors", "MacPlaneRaycastSensor"),
    "RawStereoFrame": (".stereo_depth", "RawStereoFrame"),
    "compute_disparity_absdiff": (".stereo_depth", "compute_disparity_absdiff"),
    "disparity_to_depth_mm": (".stereo_depth", "disparity_to_depth_mm"),
    "load_raw_stereo_frame": (".stereo_depth", "load_raw_stereo_frame"),
    "normalize_depth_for_preview": (".stereo_depth", "normalize_depth_for_preview"),
    "normalize_disparity_for_preview": (".stereo_depth", "normalize_disparity_for_preview"),
    "save_preview_png": (".stereo_depth", "save_preview_png"),
    "split_stereo_yuyv": (".stereo_depth", "split_stereo_yuyv"),
    "stereo_luma_from_yuyv": (".stereo_depth", "stereo_luma_from_yuyv"),
    "stereo_rgb_from_yuyv": (".stereo_depth", "stereo_rgb_from_yuyv"),
    "yuyv_to_rgb": (".stereo_depth", "yuyv_to_rgb"),
    "RolloutTrace": (".rollout", "RolloutTrace"),
    "replay_actions": (".rollout", "replay_actions"),
    "rollout_env": (".rollout", "rollout_env"),
    "BatchedArticulationState": (".state_primitives", "BatchedArticulationState"),
    "BatchedRootState": (".state_primitives", "BatchedRootState"),
    "EnvironmentOriginGrid": (".state_primitives", "EnvironmentOriginGrid"),
    "MacSimArticulationView": (".state_primitives", "MacSimArticulationView"),
    "MacSimSceneState": (".state_primitives", "MacSimSceneState"),
    "MacPlaneTerrain": (".terrain", "MacPlaneTerrain"),
    "MacWaveTerrain": (".terrain", "MacWaveTerrain"),
    "MacAnymalCFlatEnv": (".anymal_c", "MacAnymalCFlatEnv"),
    "MacAnymalCRoughEnv": (".anymal_c", "MacAnymalCRoughEnv"),
    "MacAnymalCFlatSimBackend": (".anymal_c", "MacAnymalCFlatSimBackend"),
    "MacAnymalCPolicy": (".anymal_c", "MacAnymalCPolicy"),
    "MacAnymalCTrainCfg": (".anymal_c", "MacAnymalCTrainCfg"),
    "play_anymal_c_policy": (".anymal_c", "play_anymal_c_policy"),
    "train_anymal_c_policy": (".anymal_c", "train_anymal_c_policy"),
    "MacAgibotPlaceEnv": (".manipulation", "MacAgibotPlaceEnv"),
    "MacAgibotPlaceSimBackend": (".manipulation", "MacAgibotPlaceSimBackend"),
    "MacAgibotPlaceToy2BoxEnv": (".manipulation", "MacAgibotPlaceToy2BoxEnv"),
    "MacAgibotPlaceToy2BoxSimBackend": (".manipulation", "MacAgibotPlaceToy2BoxSimBackend"),
    "MacAgibotPlaceToy2BoxTrainCfg": (".manipulation", "MacAgibotPlaceToy2BoxTrainCfg"),
    "MacAgibotPlaceUprightMugEnv": (".manipulation", "MacAgibotPlaceUprightMugEnv"),
    "MacAgibotPlaceUprightMugSimBackend": (".manipulation", "MacAgibotPlaceUprightMugSimBackend"),
    "MacAgibotPlaceUprightMugTrainCfg": (".manipulation", "MacAgibotPlaceUprightMugTrainCfg"),
    "MacH1FlatEnv": (".h1", "MacH1FlatEnv"),
    "MacH1RoughEnv": (".h1", "MacH1RoughEnv"),
    "MacH1FlatSimBackend": (".h1", "MacH1FlatSimBackend"),
    "MacH1Policy": (".h1", "MacH1Policy"),
    "MacH1TrainCfg": (".h1", "MacH1TrainCfg"),
    "play_h1_policy": (".h1", "play_h1_policy"),
    "train_h1_policy": (".h1", "train_h1_policy"),
    "MacFrankaCabinetEnv": (".manipulation", "MacFrankaCabinetEnv"),
    "MacFrankaCabinetSimBackend": (".manipulation", "MacFrankaCabinetSimBackend"),
    "MacFrankaCabinetTrainCfg": (".manipulation", "MacFrankaCabinetTrainCfg"),
    "MacFactoryPegInsertEnv": (".manipulation", "MacFactoryPegInsertEnv"),
    "MacFactoryPegInsertSimBackend": (".manipulation", "MacFactoryPegInsertSimBackend"),
    "MacFactoryPegInsertTrainCfg": (".manipulation", "MacFactoryPegInsertTrainCfg"),
    "play_factory_peg_insert_policy": (".manipulation", "play_factory_peg_insert_policy"),
    "train_factory_peg_insert_policy": (".manipulation", "train_factory_peg_insert_policy"),
    "MacFrankaBinStackEnv": (".manipulation", "MacFrankaBinStackEnv"),
    "MacFrankaBinStackSimBackend": (".manipulation", "MacFrankaBinStackSimBackend"),
    "MacFrankaBinStackTrainCfg": (".manipulation", "MacFrankaBinStackTrainCfg"),
    "MacFrankaLiftEnv": (".manipulation", "MacFrankaLiftEnv"),
    "MacFrankaLiftSimBackend": (".manipulation", "MacFrankaLiftSimBackend"),
    "MacFrankaLiftTrainCfg": (".manipulation", "MacFrankaLiftTrainCfg"),
    "MacOpenArmBiReachEnv": (".manipulation", "MacOpenArmBiReachEnv"),
    "MacOpenArmBiReachSimBackend": (".manipulation", "MacOpenArmBiReachSimBackend"),
    "MacOpenArmBiReachTrainCfg": (".manipulation", "MacOpenArmBiReachTrainCfg"),
    "MacOpenArmLiftEnv": (".manipulation", "MacOpenArmLiftEnv"),
    "MacOpenArmLiftSimBackend": (".manipulation", "MacOpenArmLiftSimBackend"),
    "MacOpenArmLiftTrainCfg": (".manipulation", "MacOpenArmLiftTrainCfg"),
    "MacOpenArmOpenDrawerEnv": (".manipulation", "MacOpenArmOpenDrawerEnv"),
    "MacOpenArmOpenDrawerSimBackend": (".manipulation", "MacOpenArmOpenDrawerSimBackend"),
    "MacOpenArmOpenDrawerTrainCfg": (".manipulation", "MacOpenArmOpenDrawerTrainCfg"),
    "MacOpenArmReachEnv": (".manipulation", "MacOpenArmReachEnv"),
    "MacOpenArmReachSimBackend": (".manipulation", "MacOpenArmReachSimBackend"),
    "MacOpenArmReachTrainCfg": (".manipulation", "MacOpenArmReachTrainCfg"),
    "MacFrankaTeddyBearLiftEnv": (".manipulation", "MacFrankaTeddyBearLiftEnv"),
    "MacFrankaTeddyBearLiftSimBackend": (".manipulation", "MacFrankaTeddyBearLiftSimBackend"),
    "MacFrankaTeddyBearLiftTrainCfg": (".manipulation", "MacFrankaTeddyBearLiftTrainCfg"),
    "MacFrankaOpenDrawerEnv": (".manipulation", "MacFrankaOpenDrawerEnv"),
    "MacFrankaOpenDrawerSimBackend": (".manipulation", "MacFrankaOpenDrawerSimBackend"),
    "MacFrankaOpenDrawerTrainCfg": (".manipulation", "MacFrankaOpenDrawerTrainCfg"),
    "MacFrankaReachEnv": (".manipulation", "MacFrankaReachEnv"),
    "MacFrankaReachPolicy": (".manipulation", "MacFrankaReachPolicy"),
    "MacFrankaReachSimBackend": (".manipulation", "MacFrankaReachSimBackend"),
    "MacFrankaReachTrainCfg": (".manipulation", "MacFrankaReachTrainCfg"),
    "MacUR10ReachEnv": (".manipulation", "MacUR10ReachEnv"),
    "MacUR10ReachSimBackend": (".manipulation", "MacUR10ReachSimBackend"),
    "MacUR10ReachTrainCfg": (".manipulation", "MacUR10ReachTrainCfg"),
    "MacUR10LongSuctionStackEnv": (".manipulation", "MacUR10LongSuctionStackEnv"),
    "MacUR10LongSuctionStackSimBackend": (".manipulation", "MacUR10LongSuctionStackSimBackend"),
    "MacUR10LongSuctionStackTrainCfg": (".manipulation", "MacUR10LongSuctionStackTrainCfg"),
    "MacUR10eGearAssembly2F140Env": (".manipulation", "MacUR10eGearAssembly2F140Env"),
    "MacUR10eGearAssembly2F140SimBackend": (".manipulation", "MacUR10eGearAssembly2F140SimBackend"),
    "MacUR10eGearAssembly2F140TrainCfg": (".manipulation", "MacUR10eGearAssembly2F140TrainCfg"),
    "MacUR10eGearAssembly2F85Env": (".manipulation", "MacUR10eGearAssembly2F85Env"),
    "MacUR10eGearAssembly2F85SimBackend": (".manipulation", "MacUR10eGearAssembly2F85SimBackend"),
    "MacUR10eGearAssembly2F85TrainCfg": (".manipulation", "MacUR10eGearAssembly2F85TrainCfg"),
    "MacUR10eDeployReachEnv": (".manipulation", "MacUR10eDeployReachEnv"),
    "MacUR10eDeployReachSimBackend": (".manipulation", "MacUR10eDeployReachSimBackend"),
    "MacUR10eDeployReachTrainCfg": (".manipulation", "MacUR10eDeployReachTrainCfg"),
    "MacUR10ShortSuctionStackEnv": (".manipulation", "MacUR10ShortSuctionStackEnv"),
    "MacUR10ShortSuctionStackSimBackend": (".manipulation", "MacUR10ShortSuctionStackSimBackend"),
    "MacUR10ShortSuctionStackTrainCfg": (".manipulation", "MacUR10ShortSuctionStackTrainCfg"),
    "MacFrankaStackEnv": (".manipulation", "MacFrankaStackEnv"),
    "MacFrankaStackSimBackend": (".manipulation", "MacFrankaStackSimBackend"),
    "MacFrankaStackTrainCfg": (".manipulation", "MacFrankaStackTrainCfg"),
    "MacFrankaStackInstanceRandomizeEnv": (".manipulation", "MacFrankaStackInstanceRandomizeEnv"),
    "MacFrankaStackInstanceRandomizeSimBackend": (".manipulation", "MacFrankaStackInstanceRandomizeSimBackend"),
    "MacFrankaStackInstanceRandomizeTrainCfg": (".manipulation", "MacFrankaStackInstanceRandomizeTrainCfg"),
    "MacFrankaStackRgbEnv": (".manipulation", "MacFrankaStackRgbEnv"),
    "MacFrankaStackRgbSimBackend": (".manipulation", "MacFrankaStackRgbSimBackend"),
    "MacFrankaStackRgbTrainCfg": (".manipulation", "MacFrankaStackRgbTrainCfg"),
    "play_franka_cabinet_policy": (".manipulation", "play_franka_cabinet_policy"),
    "play_agibot_place_toy2box_policy": (".manipulation", "play_agibot_place_toy2box_policy"),
    "play_agibot_place_upright_mug_policy": (".manipulation", "play_agibot_place_upright_mug_policy"),
    "play_franka_bin_stack_policy": (".manipulation", "play_franka_bin_stack_policy"),
    "play_franka_lift_policy": (".manipulation", "play_franka_lift_policy"),
    "play_openarm_bi_reach_policy": (".manipulation", "play_openarm_bi_reach_policy"),
    "play_openarm_lift_policy": (".manipulation", "play_openarm_lift_policy"),
    "play_openarm_open_drawer_policy": (".manipulation", "play_openarm_open_drawer_policy"),
    "play_openarm_reach_policy": (".manipulation", "play_openarm_reach_policy"),
    "play_franka_teddy_bear_lift_policy": (".manipulation", "play_franka_teddy_bear_lift_policy"),
    "play_franka_open_drawer_policy": (".manipulation", "play_franka_open_drawer_policy"),
    "play_franka_reach_policy": (".manipulation", "play_franka_reach_policy"),
    "play_ur10_reach_policy": (".manipulation", "play_ur10_reach_policy"),
    "play_ur10e_gear_assembly_2f140_policy": (".manipulation", "play_ur10e_gear_assembly_2f140_policy"),
    "play_ur10e_gear_assembly_2f140_ros_inference_policy": (
        ".manipulation",
        "play_ur10e_gear_assembly_2f140_ros_inference_policy",
    ),
    "play_ur10e_gear_assembly_2f85_policy": (".manipulation", "play_ur10e_gear_assembly_2f85_policy"),
    "play_ur10e_gear_assembly_2f85_ros_inference_policy": (
        ".manipulation",
        "play_ur10e_gear_assembly_2f85_ros_inference_policy",
    ),
    "play_ur10_long_suction_stack_policy": (".manipulation", "play_ur10_long_suction_stack_policy"),
    "play_ur10_short_suction_stack_policy": (".manipulation", "play_ur10_short_suction_stack_policy"),
    "play_ur10e_deploy_reach_policy": (".manipulation", "play_ur10e_deploy_reach_policy"),
    "play_ur10e_deploy_reach_ros_inference_policy": (".manipulation", "play_ur10e_deploy_reach_ros_inference_policy"),
    "play_franka_stack_policy": (".manipulation", "play_franka_stack_policy"),
    "play_franka_stack_blueprint_policy": (".manipulation", "play_franka_stack_blueprint_policy"),
    "play_franka_stack_instance_randomize_policy": (".manipulation", "play_franka_stack_instance_randomize_policy"),
    "play_franka_stack_rgb_policy": (".manipulation", "play_franka_stack_rgb_policy"),
    "play_franka_stack_skillgen_policy": (".manipulation", "play_franka_stack_skillgen_policy"),
    "play_franka_stack_visuomotor_cosmos_policy": (".manipulation", "play_franka_stack_visuomotor_cosmos_policy"),
    "play_franka_stack_visuomotor_policy": (".manipulation", "play_franka_stack_visuomotor_policy"),
    "train_franka_cabinet_policy": (".manipulation", "train_franka_cabinet_policy"),
    "train_agibot_place_toy2box_policy": (".manipulation", "train_agibot_place_toy2box_policy"),
    "train_agibot_place_upright_mug_policy": (".manipulation", "train_agibot_place_upright_mug_policy"),
    "train_franka_bin_stack_policy": (".manipulation", "train_franka_bin_stack_policy"),
    "train_franka_lift_policy": (".manipulation", "train_franka_lift_policy"),
    "train_openarm_bi_reach_policy": (".manipulation", "train_openarm_bi_reach_policy"),
    "train_openarm_lift_policy": (".manipulation", "train_openarm_lift_policy"),
    "train_openarm_open_drawer_policy": (".manipulation", "train_openarm_open_drawer_policy"),
    "train_openarm_reach_policy": (".manipulation", "train_openarm_reach_policy"),
    "train_franka_teddy_bear_lift_policy": (".manipulation", "train_franka_teddy_bear_lift_policy"),
    "train_franka_open_drawer_policy": (".manipulation", "train_franka_open_drawer_policy"),
    "train_franka_reach_policy": (".manipulation", "train_franka_reach_policy"),
    "train_ur10_reach_policy": (".manipulation", "train_ur10_reach_policy"),
    "train_ur10e_gear_assembly_2f140_policy": (".manipulation", "train_ur10e_gear_assembly_2f140_policy"),
    "train_ur10e_gear_assembly_2f140_ros_inference_policy": (
        ".manipulation",
        "train_ur10e_gear_assembly_2f140_ros_inference_policy",
    ),
    "train_ur10e_gear_assembly_2f85_policy": (".manipulation", "train_ur10e_gear_assembly_2f85_policy"),
    "train_ur10e_gear_assembly_2f85_ros_inference_policy": (
        ".manipulation",
        "train_ur10e_gear_assembly_2f85_ros_inference_policy",
    ),
    "train_ur10_long_suction_stack_policy": (".manipulation", "train_ur10_long_suction_stack_policy"),
    "train_ur10_short_suction_stack_policy": (".manipulation", "train_ur10_short_suction_stack_policy"),
    "train_ur10e_deploy_reach_policy": (".manipulation", "train_ur10e_deploy_reach_policy"),
    "train_ur10e_deploy_reach_ros_inference_policy": (".manipulation", "train_ur10e_deploy_reach_ros_inference_policy"),
    "train_franka_stack_policy": (".manipulation", "train_franka_stack_policy"),
    "train_franka_stack_blueprint_policy": (".manipulation", "train_franka_stack_blueprint_policy"),
    "train_franka_stack_instance_randomize_policy": (".manipulation", "train_franka_stack_instance_randomize_policy"),
    "train_franka_stack_rgb_policy": (".manipulation", "train_franka_stack_rgb_policy"),
    "train_franka_stack_skillgen_policy": (".manipulation", "train_franka_stack_skillgen_policy"),
    "train_franka_stack_visuomotor_cosmos_policy": (".manipulation", "train_franka_stack_visuomotor_cosmos_policy"),
    "train_franka_stack_visuomotor_policy": (".manipulation", "train_franka_stack_visuomotor_policy"),
    "MacCartpoleEnv": (".cartpole", "MacCartpoleEnv"),
    "MacCartpoleCameraEnv": (".cartpole_camera", "MacCartpoleCameraEnv"),
    "MacCartpoleSyntheticCamera": (".cartpole_camera", "MacCartpoleSyntheticCamera"),
    "MacCartpolePolicy": (".cartpole", "MacCartpolePolicy"),
    "MacCartpoleSimBackend": (".cartpole", "MacCartpoleSimBackend"),
    "MacCartpoleTrainCfg": (".cartpole", "MacCartpoleTrainCfg"),
    "play_cartpole_policy": (".cartpole", "play_cartpole_policy"),
    "train_cartpole_policy": (".cartpole", "train_cartpole_policy"),
    "MacCartDoublePendulumEnv": (".cart_double_pendulum", "MacCartDoublePendulumEnv"),
    "MacCartDoublePendulumSimBackend": (".cart_double_pendulum", "MacCartDoublePendulumSimBackend"),
    "MacQuadcopterEnv": (".quadcopter", "MacQuadcopterEnv"),
    "MacQuadcopterSimBackend": (".quadcopter", "MacQuadcopterSimBackend"),
    "SHOWCASE_CFGS": (".showcase", "SHOWCASE_CFGS"),
    "BoxBoxEnvCfg": (".showcase", "BoxBoxEnvCfg"),
    "BoxDiscreteEnvCfg": (".showcase", "BoxDiscreteEnvCfg"),
    "BoxMultiDiscreteEnvCfg": (".showcase", "BoxMultiDiscreteEnvCfg"),
    "DictBoxEnvCfg": (".showcase", "DictBoxEnvCfg"),
    "DictDiscreteEnvCfg": (".showcase", "DictDiscreteEnvCfg"),
    "DictMultiDiscreteEnvCfg": (".showcase", "DictMultiDiscreteEnvCfg"),
    "DiscreteBoxEnvCfg": (".showcase", "DiscreteBoxEnvCfg"),
    "DiscreteDiscreteEnvCfg": (".showcase", "DiscreteDiscreteEnvCfg"),
    "DiscreteMultiDiscreteEnvCfg": (".showcase", "DiscreteMultiDiscreteEnvCfg"),
    "MacCartpoleShowcaseEnv": (".showcase", "MacCartpoleShowcaseEnv"),
    "MultiDiscreteBoxEnvCfg": (".showcase", "MultiDiscreteBoxEnvCfg"),
    "MultiDiscreteDiscreteEnvCfg": (".showcase", "MultiDiscreteDiscreteEnvCfg"),
    "MultiDiscreteMultiDiscreteEnvCfg": (".showcase", "MultiDiscreteMultiDiscreteEnvCfg"),
    "TupleBoxEnvCfg": (".showcase", "TupleBoxEnvCfg"),
    "TupleDiscreteEnvCfg": (".showcase", "TupleDiscreteEnvCfg"),
    "TupleMultiDiscreteEnvCfg": (".showcase", "TupleMultiDiscreteEnvCfg"),
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str):
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(target[0], __name__)
    value = getattr(module, target[1])
    globals()[name] = value
    return value
